### ISSUE TITLE
Trigger Event with Directives [it isn't a known property]

### ISSUE THREAD

**Issue by AlexisP98** [CommandersAct/ngx-tag-commander#22]
Hi,
I've already installed the library and it looks very good, setTcsVars works fine, but when I try to capture events with DIRECTIVES this error appears: 

- "Can't bind to 'tcEventLabel' since it isn't a known property'" (i'm trying to attach it to buttons, like below).
- "Can't bind to 'tcEvent' since it isn't a known property'" (i'm trying to attach it to buttons, like below).
- "Can't bind to 'tcEventObj' since it isn't a known property'" (i'm trying to attach it to buttons, like below).

I also import the Module in my app.module.ts as Documentation said, in fact setTcVars (for example) works as excepted but directives not.

`<button class="button" type="submit" (click)="formSubmit()"
          [tcEvent]="'RECALL'" [tcEventLabel]="'RECALL'" [tcEventObj]="{text: 'string'}">
          TEST
        </button>`

If I try the first method, putting **captureEvent** function, I don't know how to pass element (id? class? tag name? idk), Docs say let element = 'button' but if I do this it takes all buttons in the view.

Thank you very much for your time,
best regards Alessio.

**Comment by tmrdlt** [comment]
Hello @AlexisP98,

I know your issue is already quite old, so apologies for the late respone. Are you still having this issue?
If yes, it would be great if you could provide us with a minimum example, as I wasn't able to reproduce it with the current version of the library.

Best regards,
Tmrldt

**Comment by thepiwo** [comment]
I will close this for now, feel free to reopen if the issue persists
