### ISSUE TITLE
Ivy Distribution for later Angular versions 

### ISSUE THREAD

**Issue by cassarreb** [CommandersAct/ngx-tag-commander#48]
Hi,

Do you plan to release an Ivy Distribution of this library for the later versions of Angular (e.g. Angular 13)?

Thanks,
Rebecca

**Comment by thepiwo** [comment]
With version 1.4.0 (https://github.com/CommandersAct/ngx-tag-commander/releases/tag/v1.4.0) we migrated the example to angular 15 and changed the library to be built using partial ivy builds as recommended by angular. Please re-open the issue if something doesn't work for you.
