### ISSUE TITLE
Angular 14

### ISSUE THREAD

**Issue by benjaminlefevre** [CommandersAct/ngx-tag-commander#52]
Can we expect a version of the lib migrated to angular 14?

**Comment by thepiwo** [comment]
The library should be compatible as is, with version 1.4.0 (https://github.com/CommandersAct/ngx-tag-commander/releases/tag/v1.4.0) we migrated the example to angular 15 and changed the library to be built using partial ivy builds as recommended by angular. Please let us know if something doesn't work for you.

**Comment by UnleashSpirit** [comment]
Hi,
It seems impossible to use it with angular 14
ng build gives me this 

```
Error: node_modules/ngx-tag-commander/lib/tc-event.directive/tc-event.directive.d.ts:13:18 - error TS2707: Generic type 'ɵɵDirectiveDeclaration' requires between 6 and 8 type arguments.

13     static ɵdir: i0.ɵɵDirectiveDeclaration<TcEventDirective, "[tcEvent]", never, { "tcEvent": "tcEvent"; "tcEventLabel": "tcEventLabel"; "tcEventObj": "tcEventObj"; }, {}, never, never, false, never>;
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/ngx-tag-commander/lib/tc-set-vars.directive/tc-set-vars.directive.d.ts:11:18 - error TS2707: Generic type 'ɵɵDirectiveDeclaration' requires between 6 and 8 type arguments.

11     static ɵdir: i0.ɵɵDirectiveDeclaration<TcSetVarsDirective, "[tcSetVars]", never, { "tcSetVars": "tcSetVars"; }, {}, never, never, false, never>;
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~```

**Comment by thepiwo** [comment]
@benjaminlefevre @UnleashSpirit thanks for your patience, I managed to reproduce, debug and fix the issue, you can find the PR here, we will coordinate a release soon. https://github.com/CommandersAct/ngx-tag-commander/pull/61

**Comment by thepiwo** [comment]
we releases `2.0.0` with the fix included, please let me know if there are any other issues with it. https://github.com/CommandersAct/ngx-tag-commander/releases/tag/v2.0.0

**Comment by thepiwo** [comment]
@benjaminlefevre @UnleashSpirit does the version `2.0.0` resolve your issues?

**Comment by benjaminlefevre** [comment]
it's fine for me :)
I agree to close the ticket
